import pytest

from text.game_parser import parse_game


game_data = [
    (
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        set(),
    ),
    ("CoC", {"COC"}),
    ("3.5", {"3.5"}),
    ("3e", {"3E"}),
    ("4e", {"4E"}),
    ("5e", {"5E"}),
    ("PF1e", {"PF1E"}),
    ("PF2e", {"PF2E"}),
    ("BitD", {"BITD"}),
    ("BRP", {"BRP"}),
    ("CofD", {"COFD"}),
    ("Cyberpunk", {"CYBERPUNK"}),
    ("DLC", {"DLC", "FLEXIBLE"}),
    ("DLR", {"DLR", "FLEXIBLE"}),
    ("DCC", {"DCC"}),
    ("DW", {"DW"}),
    ("ODND", {"ODND"}),
    ("ADND", {"ADND"}),
    ("BX", {"BX"}),
    ("DND2e", {"DND2E"}),
    ("Earthdawn", {"EARTHDAWN", "FLEXIBLE"}),
    ("Fate", {"FATE"}),
    ("Feast", {"FEAST", "FLEXIBLE"}),
    ("FWS", {"FWS", "FLEXIBLE"}),
    ("GURPS", {"GURPS"}),
    ("L5R", {"L5R", "FLEXIBLE"}),
    ("MCC", {"MCC", "FLEXIBLE"}),
    ("MotW", {"MOTW"}),
    ("MM3", {"MM3"}),
    ("Numenera", {"NUMENERA"}),
    ("OSR", {"OSR"}),
    ("SavageWorlds", {"SAVAGEWORLDS"}),
    ("SWADE", {"SWADE", "SAVAGEWORLDS"}),
    ("Shadowrun", {"SHADOWRUN"}),
    ("SWD", {"SWD", "SAVAGEWORLDS"}),
    ("SR3", {"SR3", "SHADOWRUN"}),
    ("SR4", {"SR4", "SHADOWRUN"}),
    ("SR5", {"SR5", "SHADOWRUN"}),
    ("SR6", {"SR6", "SHADOWRUN"}),
    ("Starfinder", {"STARFINDER"}),
    ("SWRPG", {"SWRPG"}),
    ("SWN", {"SWN"}),
    ("40K", {"40K"}),
    ("WoD", {"WOD"}),
    ("3e, 4e 5e", {"3E", "4E", "5E"}),
    ("3-5", set()),
    ("other", set()),
    ("(other)", {"FLEXIBLE"}),
    ("[other]", {"FLEXIBLE"}),
    ("<OTHER>", {"FLEXIBLE"}),
    ("{other}", {"FLEXIBLE"}),
    ("flexible", set()),
    ("(flexible)", {"FLEXIBLE"}),
    ("<Flexible>", {"FLEXIBLE"}),
    ("{Flexible}", {"FLEXIBLE"}),
    ("[FLEXIBLE]", {"FLEXIBLE"}),
    ("[Flexible Time(GMT-5)]", set()),
    ("1DND", {"5E 2024"}),
    ("5e.24", {"5E 2024"}),
    ("5e 24", {"5E 2024"}),
    ("5e 2024", {"5E 2024"}),
    ("5.5e", {"5E 2024"}),
    ("5e 14/24", {"5E", "5E 2024"}),
    ("5e 24/14", {"5E", "5E 2024"}),
]


@pytest.mark.parametrize("text,game", game_data)
def test_parse_game(text, game):
    assert parse_game(text) == game
