name: Continuous Integration

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    branches: [main]
    types: 
      - completed


jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      -
        name: Update Stack
        run: curl -X POST ${{ secrets.WEBHOOK_URL }}
