name: Continuous Integration

on:
  workflow_run:
    workflows: ["Build and Test"]
    branches: [main]
    types: 
      - completed


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hunterreadca/lfg-notify-bot:latest
          platforms: linux/amd64,linux/arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Update Stack
        run: curl -X POST https://portainer.readpnw.dev/api/stacks/webhooks/6a95f56b-4086-4993-8dae-35106edd5c33
